# -*- coding: utf-8 -*-
"""BBS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KfdzLj0VQdrl8SZcGohOSsf7OaF4EJe
"""

class BBS:
    def __init__(self, seed, start=100, end=200):
        self.seed = seed
        self.start = start
        self.end = end
        self.getPrimes()
       

    #Generates prime numbers between start and end
    def generate_primes(self, start, end):
        primes = []
        for i in range(start, end):
            isPrime = True
            for num in range(2,int(i/2)):
                if i%num==0:
                    isPrime = False
            if isPrime:
                primes.append(i)
        return primes

    # The two prime numbers p and q, should both be congruent to 3 modulo 4
    def getPrimes(self):
        primes = self.generate_primes(self.start, self.end)
        pq = []
        while len(pq) < 2:
            for prime in primes:
                if prime % 4 == 3:
                    pq.append(prime)
        self.p = pq[0]
        self.q = pq[1]

    def Generator(self): 
        M = self.p*self.q
        x = self.seed
        while(True):
            x = (x**2)%M
            yield x 
        
if __name__ == "__main__":
    bbs = BBS(286, 100, 200)
    gen = bbs.Generator()
    for _ in range(0,10):
        x = next(gen)
        print(x)